#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Checklist.cshtml")]
    public partial class _Views_Shared_Checklist_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Checklist_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Checklist.cshtml"
  
    ViewBag.Title = "Checklist";
    Layout = ViewBag.FinanceLayoutPath;

            
            #line default
            #line hidden
WriteLiteral(@"
<style>
    iframe {
        display: block;
        margin: 1em 0;
        width: 800px;
        height: 800px;
        border: 1px solid #ccc;
    }

    .checklist.segment .form:not(.unstyled),
    .checklist.segment .message {
        max-width: 800px;
    }



    .choices {
        display: flex;
    }

    .choice {
        background: #999;
        padding: 0.5em 1.25em;
        cursor: pointer;
        color: #eee;
    }

        .choice.active,
        .choice:hover {
            background: #777;
            color: #eee;
        }

        .selection.group .field:last-child {
            padding-bottom: 1em;
        }
</style>
<div");

WriteLiteral(" class=\"ui attached page checklist segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge title header\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui positive message\"");

WriteLiteral(">The transaction was posted successfully.</div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui basic  buttons\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"ui basic view transaction button\"");

WriteLiteral("></a>\r\n        <a");

WriteLiteral(" class=\"ui basic add new button\"");

WriteLiteral("></a>\r\n        <a");

WriteLiteral(" class=\"ui basic withdraw button\"");

WriteLiteral(" onclick=\"alert(\'todo\');\"");

WriteLiteral(">Cancel/Withdraw Transaction</a>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Notes</div>\r\n    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(">You haven\'t left a note yet.</div>\r\n    <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n            <textarea");

WriteLiteral(" rows=\"2\"");

WriteLiteral("></textarea>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Add Note</div>\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Documents</div>\r\n    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(">No document(s) found.</div>\r\n    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Upload a New Document</div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Reminder</div>\r\n    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(">No reminder was set.</div>\r\n    <div");

WriteLiteral(" class=\"ui green add reminder button\"");

WriteLiteral(">Create a New Reminder</div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Advice</div>\r\n    <iframe");

WriteLiteral(" id=\"ReportIFrame\"");

WriteLiteral("></iframe>\r\n    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Email Me This Document</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"ui reminder small modal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n        <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">Create a New Reminder</div>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui padded unstyled form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label>Title</label>\r\n                <input");

WriteLiteral(" placeholder=\"Remind Me About\"");

WriteLiteral("/>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"selection group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Whom to Remind?</label>\r\n                    <div");

WriteLiteral(" class=\"single selection choices\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" data-selection=\"\"");

WriteLiteral(" class=\"active choice\"");

WriteLiteral(">Only Me</div>\r\n                        <div");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" data-selection=\"role\"");

WriteLiteral(" class=\"choice\"");

WriteLiteral(">Selected Role(s)</div>\r\n                        <div");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" data-selection=\"user\"");

WriteLiteral(" class=\"choice\"");

WriteLiteral(">Selected Users(s)</div>\r\n                    </div>\r\n                </div>\r\n   " +
"             <div");

WriteLiteral(" class=\"role selection field\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                    <label>Select Roles</label>\r\n                    <select");

WriteLiteral(" class=\"ui collapsing select dropdown\"");

WriteLiteral("></select>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user selection field\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                    <label>Select Users</label>\r\n                    <select");

WriteLiteral(" class=\"ui collapsing select dropdown\"");

WriteLiteral("></select>\r\n                </div>                \r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label>Starts From</label>\r\n                <div");

WriteLiteral(" class=\"fields\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"three wide field\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" value=\"d\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"two wide field\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"time\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label>Ends On</label>\r\n                <div");

WriteLiteral(" class=\"fields\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"three wide field\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" value=\"7d\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"two wide field\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"time\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label>Enter Description for Reminder</label>\r\n               " +
" <textarea></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"selection group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Repeat?</label>\r\n                    <div");

WriteLiteral(" class=\"single selection choices\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" data-selection=\"\"");

WriteLiteral(" class=\"active choice\"");

WriteLiteral(">No</div>\r\n                        <div");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" data-selection=\"repeat.hour.value\"");

WriteLiteral(" class=\"choice\"");

WriteLiteral(">Hour</div>\r\n                        <div");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" data-selection=\"repeat.day.value\"");

WriteLiteral(" class=\"choice\"");

WriteLiteral(">Day</div>\r\n                    </div>\r\n                </div>\r\n                <" +
"div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"four fields\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"repeat hour value selection field\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                            <label>Repeat Every</label>\r\n                     " +
"       <input/>\r\n                            <label>hours</label>\r\n             " +
"           </div>\r\n                        <div");

WriteLiteral(" class=\"repeat day value selection field\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                            <label>Repeat Every</label>\r\n                     " +
"       <input />\r\n                            <label>days</label>\r\n             " +
"           </div>                        \r\n                        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                            <label>Remind Me at Least</label>\r\n               " +
"             <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"2\"");

WriteLiteral(" />\r\n                            <label>hours before the schedule</label>\r\n      " +
"                  </div>\r\n                    </div>\r\n                </div>\r\n  " +
"          </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui checkbox\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" />\r\n                    <label>Display This Reminder to Other Users</label>\r\n   " +
"             </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui checkbox\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" />\r\n                    <label>Send Me an Email</label>\r\n                </div>\r" +
"\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui checkbox\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral("  />\r\n                    <label>Including Other Participants</label>\r\n          " +
"      </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui checkbox\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" />\r\n                    <label>Attach All Documents</label>\r\n                </d" +
"iv>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui deny button\"");

WriteLiteral(">Cancel</div>\r\n        <div");

WriteLiteral(" class=\"ui positive button\"");

WriteLiteral(@">OK</div>
    </div></div>
<script>
    function prepareChecklist(model) {
        $("".title.header"").html(model.Title);
        $("".view.transaction.button"").html(model.ViewText);
        $("".view.transaction.button"").attr(""href"", model.ViewUrl);
        $("".add.new.button"").html(model.AddNewText);
        $("".add.new.button"").attr(""href"", model.AddNewUrl);
        $(""#ReportIFrame"").attr(""src"", model.ReportPath);

        if (!model.ViewText) {
            $("".view.transaction.button"").remove();
        };

        if (!model.AddNewText) {
            $("".add.new.button"").remove();
        };
    };

    $("".selection.choices .choice"").off(""click"").on(""click"", function () {
        const el = $(this);
        const singleSelection = el.parent().hasClass(""single"");

        if (singleSelection) {
            el.parent().find("".choice"").removeClass(""active"");
        };

        el.toggleClass(""active"");

        const active = el.hasClass(""active"");
        if (!active) {
            return;
        };

        const selection = el.attr(""data-selection"");

        el.closest("".selection.group"").find("".selection.field"").hide();

        if (selection) {
            $(""."" + selection + "".selection.field"").show();
        };
    });

    $("".add.reminder.button"").off(""click"").on(""click"", function() {
        $("".reminder.modal"").modal(""show"");
        $("".time"").timepicker('setTime', new Date());
    });
</script>");

        }
    }
}
#pragma warning restore 1591
