#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Checklist.cshtml")]
    public partial class _Views_Shared_Checklist_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Checklist_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Checklist.cshtml"
  
    ViewBag.Title = "Checklist";
    Layout = ViewBag.FinanceLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\niframe{\r\n\tdisplay: block;\r\n\tmargin:1em 0;\r\n\twidth: 800px;\r\n\theight: 80" +
"0px;\r\n\tborder:1px solid #ccc;\r\n}    \r\n</style>\r\n<div");

WriteLiteral(" class=\"ui attached page segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge title header\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui positive message\"");

WriteLiteral(">The transaction was posted successfully.</div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui basic  buttons\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"ui basic view transaction button\"");

WriteLiteral("></a>\r\n        <a");

WriteLiteral(" class=\"ui basic add new button\"");

WriteLiteral("></a>\r\n        <a");

WriteLiteral(" class=\"ui basic withdraw button\"");

WriteLiteral(" onclick=\"alert(\'todo\');\"");

WriteLiteral(">Cancel/Withdraw Transaction</a>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Notes</div>\r\n    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(">No note(s) found.</div>\r\n    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Add Note</div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Documents</div>\r\n    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(">No document(s) found.</div>\r\n    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Upload a New Document</div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Reminder</div>\r\n    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(">Remind me about this transaction.</div>\r\n    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Add Reminder</div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Advice</div>\r\n    <iframe");

WriteLiteral(" id=\"ReportIFrame\"");

WriteLiteral("></iframe>\r\n    <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(@">Send Email</div>
</div>

<script>
    function prepareChecklist(model) {
        $("".title.header"").html(model.Title);
        $("".view.transaction.button"").html(model.ViewText);
        $("".view.transaction.button"").attr(""href"", model.ViewUrl);
        $("".add.new.button"").html(model.AddNewText);
        $("".add.new.button"").attr(""href"", model.AddNewUrl);
        $(""#ReportIFrame"").attr(""src"", model.ReportPath);

        if (!model.ViewText) {
            $("".view.transaction.button"").remove();
        };

        if (!model.AddNewText) {
            $("".add.new.button"").remove();
        };
    };
</script>");

        }
    }
}
#pragma warning restore 1591
