#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    #line 1 "..\..\Views\Shared\Verification.cshtml"
    using MixERP.Finance.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Verification.cshtml")]
    public partial class _Views_Shared_Verification_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Verification_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\Verification.cshtml"
  
    ViewBag.Title = "Verification";
    Layout = ViewBag.FinanceLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\Shared\Verification.cshtml"
Write(Html.PartialView("Shared/JournalView.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"ActionModal\"");

WriteLiteral(" class=\"ui modal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui massive red header\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui inverted red content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui blue large dividing header\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ReasonTextArea\"");

WriteLiteral(">Verification Reason</label>\r\n                <textarea");

WriteLiteral(" id=\"ReasonTextArea\"");

WriteLiteral("></textarea>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"ui red cancel button\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"VerifyButton\"");

WriteLiteral(" class=\"ui green ok button\"");

WriteLiteral(" value=\"Verify\"");

WriteLiteral(" title=\"CTRL + RETURN\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    var reasonTextArea = $(\"" +
"#ReasonTextArea\");\r\n    var journalView = $(\"#JournalView\");\r\n    var modal = $(" +
"\"#ActionModal\");\r\n    var verifyButton = $(\"#VerifyButton\");\r\n    var tranId;\r\n " +
"   var approve;\r\n\r\n    verifyButton.click(function () {\r\n        function getMod" +
"el() {\r\n            const reason = reasonTextArea.val();\r\n\r\n            return {" +
"\r\n                TranId: tranId,\r\n                Reason: reason\r\n            }" +
";\r\n        };\r\n\r\n        function request(model, type) {\r\n            const url " +
"= \"/dashboard/finance/tasks/verification/\" + type;\r\n            const data = JSO" +
"N.stringify(model);\r\n\r\n            return window.getAjaxRequest(url, \"POST\", dat" +
"a);\r\n        }\r\n\r\n        const model = getModel();\r\n        const type = approv" +
"e ? \"approve\" : \"reject\";\r\n\r\n        const ajax = request(model, type);\r\n\r\n     " +
"   ajax.success(function (response) {\r\n            var cascadingTranId = parseFl" +
"oat(response);\r\n\r\n            if (cascadingTranId) {\r\n                journalVie" +
"w.find(\"tr td:nth-child(3)\").each(function (i) {\r\n                    const tran" +
"Id = parseFloat($(this).text() || 0);\r\n\r\n                    if (cascadingTranId" +
" === tranId) {\r\n                        removeRow(i);\r\n                    };\r\n " +
"               });\r\n            };\r\n\r\n            journalView.find(\"input:checke" +
"d\").first().parent().parent().parent().remove();\r\n            hideModal();\r\n    " +
"    });\r\n\r\n        ajax.fail(function (xhr) {\r\n            window.logAjaxErrorMe" +
"ssage(xhr);\r\n        });\r\n\r\n        return false;\r\n    });\r\n    shortcut.add(\"CT" +
"RL+RETURN\", function () {\r\n        if (modal.is(\":visible\")) {\r\n            veri" +
"fyButton.trigger(\"click\");\r\n        };\r\n    });\r\n\r\n    function showModal() {\r\n " +
"       const header = modal.find(\".ui.massive.header\");\r\n        const subheader" +
" = modal.find(\".ui.dividing.header\");\r\n\r\n        header.html(\"Reject Transaction" +
"\");\r\n        subheader.html(window.stringFormat(\"TranId: #{0}\", tranId));\r\n     " +
"   header.removeClass(\"green\").addClass(\"red\");\r\n\r\n        if (approve) {\r\n     " +
"       header.html(\"Approve Transaction\");\r\n            header.removeClass(\"red\"" +
").addClass(\"green\");\r\n        };\r\n\r\n        modal.modal(\'setting\', \'closable\', f" +
"alse).modal(\'show\');\r\n    };\r\n\r\n    function getSelectedItem() {\r\n        const " +
"selected = journalView.find(\"input:checked\").first();\r\n\r\n        if (selected.le" +
"ngth) {\r\n            const row = selected.parent().parent().parent();\r\n         " +
"   const id = row.find(\"td:nth-child(3)\").html();\r\n            return parseInt(i" +
"d);\r\n        };\r\n\r\n        return 0;\r\n    };\r\n\r\n    function removeRow(index, ca" +
"llback) {\r\n        journalView.find(\"tr\").eq(index + 1).addClass(\"negative\").fad" +
"eOut(500, function () {\r\n            $(this).remove();\r\n\r\n            if (typeof" +
" (callback) === \"function\") {\r\n                callback();\r\n            };\r\n    " +
"    });\r\n    };\r\n\r\n    function hideModal() {\r\n        modal.modal(\"hide\");\r\n   " +
" };\r\n\r\n    function prepareVerification(model) {\r\n        function getButton(id," +
" text) {\r\n            const button = $(\"<a class=\'ui basic button\' />\");\r\n      " +
"      button.attr(\"id\", id);\r\n            button.html(text);\r\n\r\n            retu" +
"rn button;\r\n        };\r\n\r\n        $(\"#StatusInputText\").val(\"Unverified\");\r\n\r\n\r\n" +
"        const approveButton = getButton(\"ApproveButton\", \"Approve\");\r\n        co" +
"nst rejectButton = getButton(\"RejectButton\", \"Reject\");\r\n\r\n        $(\"#AddNewBut" +
"ton\").after(approveButton);\r\n        approveButton.after(rejectButton);\r\n\r\n\r\n   " +
"     approveButton.click(function () {\r\n            tranId = getSelectedItem();\r" +
"\n\r\n            if (tranId) {\r\n                approve = true;\r\n                s" +
"howModal();\r\n            };\r\n        });\r\n\r\n        rejectButton.click(function " +
"() {\r\n            tranId = getSelectedItem();\r\n\r\n            if (tranId) {\r\n    " +
"            approve = false;\r\n                showModal();\r\n            };\r\n    " +
"    });\r\n\r\n\r\n        window.prepareView(model);\r\n    };\r\n</script>");

        }
    }
}
#pragma warning restore 1591
