#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Tasks\ExchangeRates\Index.cshtml"
    using Frapid.ApplicationState.Cache;
    
    #line default
    #line hidden
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/ExchangeRates/Index.cshtml")]
    public partial class _Views_Tasks_ExchangeRates_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_ExchangeRates_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\ExchangeRates\Index.cshtml"
  
    ViewBag.Title = "Exchange Rates";
    Layout = ViewBag.FinanceLayoutPath;
    var meta = AppUsers.GetCurrent();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"ui attached page segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">\r\n        Exchange Rates\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"OfficeInputText\"");

WriteLiteral(">\r\n                    Office\r\n                </label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OfficeInputText\"");

WriteLiteral(" readonly=\"readonly\"");

WriteAttribute("value", Tuple.Create(" value=\"", 638), Tuple.Create("\"", 662)
            
            #line 22 "..\..\Views\Tasks\ExchangeRates\Index.cshtml"
    , Tuple.Create(Tuple.Create("", 646), Tuple.Create<System.Object, System.Int32>(meta.OfficeName
            
            #line default
            #line hidden
, 646), false)
);

WriteLiteral(" runat=\"server\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"CurrencyInputText\"");

WriteLiteral(">\r\n                    Base Currency\r\n                </label>\r\n                <" +
"input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CurrencyInputText\"");

WriteLiteral(" readonly=\"readonly\"");

WriteAttribute("value", Tuple.Create(" value=\"", 923), Tuple.Create("\"", 949)
            
            #line 28 "..\..\Views\Tasks\ExchangeRates\Index.cshtml"
      , Tuple.Create(Tuple.Create("", 931), Tuple.Create<System.Object, System.Int32>(meta.CurrencyCode
            
            #line default
            #line hidden
, 931), false)
);

WriteLiteral(" runat=\"server\"");

WriteLiteral(" />\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ApiSelect\"");

WriteLiteral(">\r\n                    Select API\r\n                </label>\r\n                <sel" +
"ect");

WriteLiteral(" id=\"ApiSelect\"");

WriteLiteral(" class=\"ui dropdown\"");

WriteLiteral("></select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"RequestButton\"");

WriteLiteral(">\r\n                    &nbsp;\r\n                </label>\r\n                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"RequestButton\"");

WriteLiteral(" value=\"Request\"");

WriteLiteral(" class=\"ui pink button\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <table");

WriteLiteral(" class=\"ui very compact small striped collapsing table\"");

WriteLiteral(" id=\"ExchangeRatesGridView\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>Currency Code</th>
                <th>Symbol</th>
                <th>Currency Name</th>
                <th>Hundredth Name</th>
                <th>Exchange Rate</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"SaveButton\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" />\r\n\r\n    <script>\r\n        var exchangeRatesGridView = $(\"#ExchangeRatesGridVie" +
"w\");\r\n        var currencyInputText = $(\"#CurrencyInputText\");\r\n        var url;" +
"\r\n        var data;\r\n        var moduleSelect = $(\"#ModuleSelect\");\r\n        var" +
" requestButton = $(\"#RequestButton\");\r\n        var saveButton = $(\"#SaveButton\")" +
";\r\n\r\n        $(document).ready(function () {\r\n            loadCurrencies();\r\n   " +
"     });\r\n\r\n        function bindCurrencies(currencies) {\r\n            $(currenc" +
"ies).each(function () {\r\n                addRow(this.CurrencyCode, this.Currency" +
"Symbol, this.CurrencyName, this.HundredthName);\r\n            });\r\n        };\r\n\r\n" +
"        function addRow(currencyCode, currencySymbol, currencyName, hundredthNam" +
"e) {\r\n            exchangeRatesGridView.find(\"tbody\").append(window.stringFormat" +
"(\"<tr class=\'ui form\'><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td><input" +
" type=\'text\' id=\'{0}ExchangRateInputText\' class=\'text-right currency\' onblur=\'di" +
"splayDescription(this);\' /></td><td></td></tr>\", currencyCode, currencySymbol, c" +
"urrencyName, hundredthName));\r\n        };\r\n\r\n        function loadCurrencies() {" +
"\r\n            function request() {\r\n                url = \"/dashboard/finance/ta" +
"sks/exchange-rates/currency-list\";\r\n\r\n                return window.getAjaxReque" +
"st(url);\r\n            };\r\n\r\n\r\n            var ajax = request();\r\n\r\n            a" +
"jax.success(function (response) {\r\n                bindCurrencies(response);\r\n  " +
"          });\r\n\r\n            ajax.fail(function (xhr) {\r\n                alert(x" +
"hr.responseText);\r\n            });\r\n\r\n        };\r\n\r\n        function displayDesc" +
"ription(element) {\r\n            var exchangeRate = window.parseFloat2($(element)" +
".val());\r\n\r\n            if (!exchangeRate) {\r\n                return;\r\n         " +
"   };\r\n\r\n            var descriptionCell = $(element).parent().parent().find(\"td" +
":nth-child(6)\");\r\n            var currencyCode = $(element).parent().parent().fi" +
"nd(\"td:nth-child(1)\").html();\r\n            var exchangeRateReverse = (1.00 / exc" +
"hangeRate).toFixed(4);\r\n\r\n            var description = exchangeRate + \" \" + cur" +
"rencyCode + \" = 1 \" + currencyInputText.val() + \" (\" + exchangeRateReverse + \" \"" +
" + currencyInputText.val() + \" = 1 \" + currencyCode + \")\";\r\n\r\n            descri" +
"ptionCell.html(description);\r\n        };\r\n\r\n        requestButton.click(function" +
" () {\r\n            window.displayMessage(\"Not implemented\");\r\n        });\r\n\r\n   " +
"     function updateExchangeRates(result) {\r\n\r\n            for (i = 0; i < resul" +
"t.length; i++) {\r\n                exchangeRatesGridView.find(\"tbody tr\").each(fu" +
"nction () {\r\n                    var currency = $(this).find(\"td:first-child\").h" +
"tml();\r\n\r\n                    if (result[i].CurrencyCode === currency) {\r\n      " +
"                  var input = $(this).find(\"input\");\r\n                        in" +
"put.val(result[i].ExchangeRate);\r\n                        input.trigger(\"blur\");" +
"\r\n                        return false;\r\n                    };\r\n               " +
" });\r\n            };\r\n        };\r\n\r\n        saveButton.click(function () {\r\n    " +
"        function request(model) {\r\n                url = \"/dashboard/finance/tas" +
"ks/exchange-rates\";\r\n\r\n                var data = JSON.stringify(model);\r\n\r\n    " +
"            return window.getAjaxRequest(url, \"POST\", data);\r\n            };\r\n\r\n" +
"            var exchangeRates = [];\r\n\r\n            exchangeRatesGridView.find(\"t" +
"body tr\").each(function () {\r\n                var currencyCode = $(this).find(\"t" +
"d:first-child\").html();\r\n                var rate = parseFloat($(this).find(\"inp" +
"ut\").val());\r\n\r\n                if (rate) {\r\n                    var exchangeRat" +
"e = new Object();\r\n                    exchangeRate.CurrencyCode = currencyCode;" +
"\r\n                    exchangeRate.Rate = rate;\r\n\r\n                    exchangeR" +
"ates.push(exchangeRate);\r\n                };\r\n            });\r\n\r\n            var" +
" ajax = request(exchangeRates);\r\n\r\n            ajax.success(function (response) " +
"{\r\n                if (response) {\r\n                    window.displaySuccess();" +
"\r\n                };\r\n            });\r\n\r\n            ajax.fail(function (xhr) {\r" +
"\n                window.logAjaxErrorMessage(xhr);\r\n            });\r\n\r\n\r\n        " +
"});\r\n\r\n    </script>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
