#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Layout.cshtml")]
    public partial class _Views_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Layout.cshtml"
  
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<div");

WriteLiteral(" class=\"finance layout container\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<script>\r\n    loadDatepicker();\r\n    setNumberFormat();\r\n</script>\r\n\r" +
"\n<div");

WriteLiteral(" class=\"ui small modal\"");

WriteLiteral(" id=\"EODModal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n    <div");

WriteLiteral(" class=\"ui icon header\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"loading spinner icon\"");

WriteLiteral("></i>\r\n        EOD Processing Has Begun\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <p>\r\n            Please close this window and save your existing work " +
"before you will be signed off automatically.\r\n        </p>\r\n        <div");

WriteLiteral(" style=\"margin-left: 300px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui circular segment\"");

WriteLiteral(" style=\"width: 120px; height: 120px;\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" class=\"ui large header\"");

WriteLiteral(" style=\"font-size: 36px;\"");

WriteLiteral("></h2>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui button\"");

WriteLiteral(">\r\n            Cancel\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui button\"");

WriteLiteral(">\r\n            OK\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" src=\"/signalr/hubs\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        var started = false;

        $.connection.baseHub.client.terminate = function (c, tenant) {

            if (window.meta.Tenant !== tenant) {
                return;
            };

            if (typeof (window.terminateListener) === ""function"") {
                window.terminateListener(c);
            };

            $(""#EODModal .circular.segment h2"").html(c + ""%"");

            if (!started) {
                $(""#EODModal"").modal(""show"");
                started = true;
            };

            if (c === 100) {
                localStorage.removeItem(""access_token"");
                window.location = ""/account/sign-out"";
            };
        };

        $.connection.hub.start().done(function () {
            if (typeof (window.connectionListener) === ""function"") {
                window.connectionListener();
            };
        });

        $.connection.hub.disconnected(function () {
            setTimeout(function () {
                $.connection.hub.start();
            }, 5000);
        });
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
