#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/BankAccounts.cshtml")]
    public partial class _Views_Setup_BankAccounts_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_BankAccounts_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\BankAccounts.cshtml"
  
    ViewBag.Title = "Bank Accounts";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"B" +
"ank Accounts\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/finance/bank-account-sc" +
"rud-view\";\r\n    scrudFactory.viewTableName = \"finance.bank_account_scrud_view\";\r" +
"\n\r\n    scrudFactory.formAPI = \"/api/forms/finance/bank-accounts\";\r\n    scrudFact" +
"ory.formTableName = \"finance.bank_accounts\";\r\n\r\n    scrudFactory.excludedColumns" +
" = [\"audit_user_id\", \"audit_ts\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    s" +
"crudFactory.allowEdit = true;\r\n\r\n    scrudFactory.live = \"BankAccountNumber\";\r\n\r" +
"\n    scrudFactory.card = {\r\n        header: \"bank_name\",\r\n        meta: \"bank_br" +
"anch\",\r\n        description: \"bank_account_number\"        \r\n    };\r\n\r\n    scrudF" +
"actory.layout = [\r\n        {\r\n            tab: \"\",\r\n            fields: [\r\n     " +
"           [\"BankAccountId\", \"\"],\r\n                [\"\", \"\"],\r\n            ]\r\n   " +
"     }\r\n    ];\r\n\r\n    scrudFactory.keys = [\r\n        {\r\n            property: \"A" +
"ccountId\",\r\n            url: \'/api/views/finance/bank-account-selector-view/disp" +
"lay-fields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n         " +
"   textField: \"Value\"\r\n        },\r\n        {\r\n            property: \"MaintainedB" +
"yUserId\",\r\n            url: \'/api/views/account/user-selector-view/display-field" +
"s\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n            textFi" +
"eld: \"Value\"\r\n        },\r\n        {\r\n            property: \"OfficeId\",\r\n        " +
"    url: \'/api/forms/core/offices/display-fields\',\r\n            data: null,\r\n   " +
"         valueField: \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n    ];\r\n" +
"\r\n\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view) {\r\n        $.get(\'/Sc" +
"rudFactory/Form.html\', function (form) {\r\n            $(\"#ScrudFactoryView\").htm" +
"l(view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n            $.cachedSc" +
"ript(\"/assets/js/scrudfactory-view.js\");\r\n            $.cachedScript(\"/assets/js" +
"/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
