#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/CashFlowHeadings.cshtml")]
    public partial class _Views_Setup_CashFlowHeadings_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_CashFlowHeadings_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\CashFlowHeadings.cshtml"
  
    ViewBag.Title = "Cash Flow Headings";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"C" +
"ash Flow Headings\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/finance/cash-flow-" +
"heading-scrud-view\";\r\n    scrudFactory.viewTableName = \"finance.cash_flow_headin" +
"g_scrud_view\";\r\n\r\n    scrudFactory.formAPI = \"/api/forms/finance/cash-flow-headi" +
"ngs\";\r\n    scrudFactory.formTableName = \"finance.cash_flow_headings\";\r\n\r\n    scr" +
"udFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n\r\n    scrudFactory.a" +
"llowDelete = true;\r\n    scrudFactory.allowEdit = true;\r\n\r\n    scrudFactory.live " +
"= \"Name\";\r\n\r\n    scrudFactory.card = {\r\n        header: \"cash_flow_heading_name\"" +
",\r\n        meta: \"cash_flow_heading_code\",\r\n        description: \"cash_flow_head" +
"ing_type\"        \r\n    };\r\n\r\n    //scrudFactory.layout = [\r\n    //    {\r\n    // " +
"       tab: \"\",\r\n    //        fields: [\r\n    //            [\"\", \"\"],\r\n    //   " +
"         [\"\", \"\"],\r\n    //        ]\r\n    //    }\r\n    //];\r\n\r\n    //scrudFactory" +
".keys = [\r\n    //    {\r\n    //        property: \"CamelCase\",\r\n    //        url:" +
" \'/api/forms/finance//display-fields\',\r\n    //        data: null,\r\n    //       " +
" valueField: \"Key\",\r\n    //        textField: \"Value\"\r\n    //    }\r\n    //];\r\n\r\n" +
"\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view) {\r\n        $.get(\'/Scru" +
"dFactory/Form.html\', function (form) {\r\n            $(\"#ScrudFactoryView\").html(" +
"view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n            $.cachedScri" +
"pt(\"/assets/js/scrudfactory-view.js\");\r\n            $.cachedScript(\"/assets/js/s" +
"crudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
