#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/CashRepositories.cshtml")]
    public partial class _Views_Setup_CashRepositories_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_CashRepositories_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\CashRepositories.cshtml"
  
    ViewBag.Title = "Cash Repositories";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"C" +
"ash Repositories\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/finance/cash-reposi" +
"tory-scrud-view\";\r\n    scrudFactory.viewTableName = \"finance.cash_repository_scr" +
"ud_view\";\r\n\r\n    scrudFactory.formAPI = \"/api/forms/finance/cash-repositories\";\r" +
"\n    scrudFactory.formTableName = \"finance.cash_repositories\";\r\n\r\n    scrudFacto" +
"ry.excludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n\r\n    scrudFactory.allowDel" +
"ete = true;\r\n    scrudFactory.allowEdit = true;\r\n\r\n    scrudFactory.live = \"Cash" +
"RepositoryName\";\r\n\r\n    scrudFactory.card = {\r\n        header: \"cash_repository_" +
"name\",\r\n        meta: \"cash_repository_code\",\r\n        description: \"office\"\r\n  " +
"      \r\n    };\r\n\r\n    scrudFactory.layout = [\r\n        {\r\n            tab: \"\",\r\n" +
"            fields: [\r\n                [\"CashRepositoryId\", \"\"],\r\n              " +
"  [\"\", \"\"],\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudFactory.keys = [\r\n    " +
"    {\r\n            property: \"OfficeId\",\r\n            url: \'/api/forms/core/offi" +
"ces/display-fields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n " +
"           textField: \"Value\"\r\n        },\r\n        {\r\n            property: \"Par" +
"entCashRepositoryId\",\r\n            url: \'/api/forms/finance/cash-repositories/di" +
"splay-fields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n       " +
"     textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory/View." +
"html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.html\', function (for" +
"m) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#ScrudFacto" +
"ryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/scrudfactory-view.j" +
"s\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n        })" +
";\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
