#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/Currencies.cshtml")]
    public partial class _Views_Setup_Currencies_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_Currencies_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\Currencies.cshtml"
  
    ViewBag.Title = "Currencies";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"C" +
"urrencies\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/core/currencies\";\r\n    scr" +
"udFactory.viewTableName = \"core.currencies\";\r\n\r\n    scrudFactory.formAPI = \"/api" +
"/forms/core/currencies\";\r\n    scrudFactory.formTableName = \"core.currencies\";\r\n\r" +
"\n    scrudFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n    scrudFac" +
"tory.skipPrimaryKey = true;\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFa" +
"ctory.allowEdit = true;\r\n\r\n    scrudFactory.live = \"CurrencyName\";\r\n\r\n    scrudF" +
"actory.card = {\r\n        header: \"CurrencyName\",\r\n        meta: \"CurrencySymbol\"" +
",\r\n        description: \"HundredthName\"        \r\n    };\r\n\r\n    //scrudFactory.la" +
"yout = [\r\n    //    {\r\n    //        tab: \"\",\r\n    //        fields: [\r\n    //  " +
"          [\"\", \"\"],\r\n    //            [\"\", \"\"],\r\n    //        ]\r\n    //    }\r\n" +
"    //];\r\n\r\n    //scrudFactory.keys = [\r\n    //    {\r\n    //        property: \"C" +
"amelCase\",\r\n    //        url: \'/api/forms/finance/display-fields\',\r\n    //     " +
"   data: null,\r\n    //        valueField: \"Key\",\r\n    //        textField: \"Valu" +
"e\"\r\n    //    }\r\n    //];\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (" +
"view) {\r\n        $.get(\'/ScrudFactory/Form.html\', function (form) {\r\n           " +
" $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#ScrudFactoryForm\").html(for" +
"m);\r\n            $.cachedScript(\"/assets/js/scrudfactory-view.js\");\r\n           " +
" $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</scr" +
"ipt>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
