#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/VerificationPolicy/Index.cshtml")]
    public partial class _Views_Tasks_VerificationPolicy_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_VerificationPolicy_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\VerificationPolicy\Index.cshtml"
  
    ViewBag.Title = "Verification Policy";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"V" +
"erification Policy\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/finance/journal-v" +
"erification-policy-scrud-view\";\r\n    scrudFactory.viewTableName = \"finance.journ" +
"al_verification_policy_scrud_view\";\r\n\r\n    scrudFactory.formAPI = \"/api/forms/fi" +
"nance/journal-verification-policy\";\r\n    scrudFactory.formTableName = \"finance.j" +
"ournal_verification_policy\";\r\n\r\n    scrudFactory.excludedColumns = [\"audit_user_" +
"id\", \"audit_ts\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allo" +
"wEdit = true;\r\n\r\n    scrudFactory.live = \"Name\";\r\n\r\n    scrudFactory.card = {\r\n " +
"       header: \"get_name_by_user_id\",\r\n        meta: \"get_office_name_by_office_" +
"id\",\r\n        description: \"ends_on\"        \r\n    };\r\n\r\n    scrudFactory.layout " +
"= [\r\n        {\r\n            tab: \"\",\r\n            fields: [\r\n                [\"J" +
"ournalVerificationPolicyId\", \"\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudF" +
"actory.keys = [\r\n        {\r\n            property: \"UserId\",\r\n            url: \'/" +
"api/views/account/user-selector-view/display-fields\',\r\n            data: null,\r\n" +
"            valueField: \"Key\",\r\n            textField: \"Value\"\r\n        },\r\n    " +
"    {\r\n            property: \"OfficeId\",\r\n            url: \'/api/forms/core/offi" +
"ces/display-fields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n " +
"           textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory" +
"/View.html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.html\', functio" +
"n (form) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#Scru" +
"dFactoryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/scrudfactory-" +
"view.js\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n    " +
"    });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
