#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/EOD/Index.cshtml")]
    public partial class _Views_Tasks_EOD_Index_cshtml : System.Web.Mvc.WebViewPage<MixERP.Finance.DTO.FrequencyDates>
    {
        public _Views_Tasks_EOD_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\EOD\Index.cshtml"
  
    ViewBag.Title = "Exchange Rates";
    Layout = ViewBag.FinanceLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" src=\"/signalr/hubs\"");

WriteLiteral(@"></script>
<style>
    .eod.messages {
        color: #666;
    }

    .eod.error.messages {
        color: #D10D89;
    }

    .eod.messages div {
        padding: 0.25em 1em;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        word-spacing: 0.12em;
        font-size: 0.87em;
        border-bottom: 1px dotted #ddd;
        display: flex;
    }

        .eod.messages div time,
        .eod.messages div span {
            display: inline-flex;
            flex-direction: column;
        }

        .eod.messages div time {
            font-weight: bold;
            padding-right: 4em;
            color: #999;
        }
</style>

<div");

WriteLiteral(" class=\"ui attached page segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui stackable grid\"");

WriteLiteral(">\r\n");

            
            #line 43 "..\..\Views\Tasks\EOD\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Tasks\EOD\Index.cshtml"
             if (!Model.NewDayStarted)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"eight wide column\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">\r\n                        Initialize EOD Processing for ");

            
            #line 48 "..\..\Views\Tasks\EOD\Index.cshtml"
                                                 Write(Model.Today.ToString("d"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(@">
                        <p>When you initialize day-end operation, the already logged-in application users including you are logged off after 120 seconds.</p>

                        <p>
                            During the day-end period, only users having elevated privilege are allowed to log-in.
                            Please do not close this window or navigate away from this page during initialization.
                        </p>


                    </div>



                    <button id = ""InitializeEODButton"" class=""ui blue button"">Initialize EOD</button>
                </div>
");

            
            #line 66 "..\..\Views\Tasks\EOD\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 67 "..\..\Views\Tasks\EOD\Index.cshtml"
             if (Model.NewDayStarted)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"eight wide column\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">Perform EOD Operation (");

            
            #line 71 "..\..\Views\Tasks\EOD\Index.cshtml"
                                                               Write(Model.Today.ToString("d"));

            
            #line default
            #line hidden
WriteLiteral(")</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"ui warning message\"");

WriteLiteral(@">
                        <p>When you perform EOD operation for a particular date, no transaction on that date or before can be altered, changed, or deleted.</p>

                        <p>
                            During EOD operation, routine tasks such as interest calculation, settlements, and report generation are performed.
                            This process is irreversible.
                        </p>
                    </div>
                    <button");

WriteLiteral(" id=\"PerformEODButton\"");

WriteLiteral(" class=\"ui small red button\"");

WriteLiteral(" onclick=\"return false;\"");

WriteLiteral(">Perform EOD</button>\r\n                </div>\r\n");

            
            #line 83 "..\..\Views\Tasks\EOD\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"sixteen wide column\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui teal progress\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"bar\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </div>\r\n\r\n\r\n");

            
            #line 94 "..\..\Views\Tasks\EOD\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Tasks\EOD\Index.cshtml"
         if (Model.NewDayStarted)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h2");

WriteLiteral(" class=\"ui blue header\"");

WriteLiteral(">EOD Console</h2>\r\n");

WriteLiteral("            <div");

WriteLiteral(" id=\"EODSegment\"");

WriteLiteral(" class=\"ui segment\"");

WriteLiteral(" style=\"height: 600px; overflow: auto;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"eod messages\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"big error message\"");

WriteLiteral("></div>\r\n");

            
            #line 102 "..\..\Views\Tasks\EOD\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var counter = 120;\r\n    var interval;\r\n    var url;\r\n    var data;\r\n    va" +
"r start;\r\n    var receivingData = true;\r\n\r\n    $(\"#EODModal\").remove();\r\n\r\n    $" +
"(function () {\r\n        var dayOperation = $.connection.dayOperationHub;\r\n      " +
"  //EOD Notices from PostgreSQL Server\r\n        dayOperation.client.getNotificat" +
"ion = function (msg, condition) {\r\n            AddItem(msg);\r\n\r\n            if (" +
"condition.toLowerCase() === \"error\") {\r\n                receivingData = false;\r\n" +
"\r\n                $(\".blue\").removeClass(\"blue\").addClass(\"red\");\r\n             " +
"   $(\"h2\").removeClass(\"blue\").addClass(\"red\");\r\n                $(\".loading\").r" +
"emoveClass(\"loading\");\r\n                $(\".progress\").removeClass(\"success\").ad" +
"dClass(\"error\");\r\n                $(\".eod.messages\").addClass(\"error\");\r\n       " +
"         $(\".big.error.message\").text(msg);\r\n            };\r\n\r\n            if (m" +
"sg === \"OK\") {\r\n                receivingData = false;\r\n                $(\".load" +
"ing\").removeClass(\"loading\");\r\n                notifyServer();\r\n            };\r\n" +
"        };\r\n\r\n        $.connection.hub.start().done(function () {\r\n            $" +
"(\"#PerformEODButton\").click(function () {\r\n                $(this).addClass(\"dis" +
"abled\");\r\n                $(\".ui.blue.header\").removeClass(\"initially hidden\");\r" +
"\n                ShowProgress(0);\r\n                dayOperation.server.performEo" +
"d();\r\n            });\r\n        });\r\n    });\r\n\r\n    //Termination Signal\r\n    fun" +
"ction terminateListener(counter) {\r\n        $(\"#PerformEODButton\").addClass(\"dis" +
"abled\");\r\n        $(\"#InitializeEODButton\").addClass(\"disabled\");\r\n\r\n        $(\'" +
".progress\').progress({\r\n            percent: counter\r\n        });\r\n    };\r\n\r\n   " +
" //Connection to EOD SignalR Hub was successful.\r\n    function connectionListene" +
"r() {\r\n        $(\"#InitializeEODButton\").removeClass(\"disabled loading\");\r\n     " +
"   $(\"#PerformEODButton\").removeClass(\"disabled loading\");\r\n\r\n        $(\"#Initia" +
"lizeEODButton\").click(function () {\r\n            function request() {\r\n         " +
"       const url = \"/dashboard/finance/tasks/eod-processing/initialize\";\r\n      " +
"          return window.getAjaxRequest(url, \"POST\");\r\n            };\r\n\r\n        " +
"    $(this).addClass(\"disabled\");\r\n            const ajax = request();\r\n\r\n      " +
"      ajax.success(function () {\r\n                start = new Date();\r\n\r\n       " +
"         interval = setInterval(sendMessage, 5000);\r\n                return;\r\n  " +
"          });\r\n\r\n            ajax.fail(function (xhr) {\r\n                window." +
"logAjaxErrorMessage(xhr);\r\n            });\r\n        });\r\n    };\r\n\r\n    var toggl" +
"e = false;\r\n\r\n    function AddItem(msg) {\r\n        const timestamp = new Date()." +
"toISOString();\r\n\r\n        var html = `<div>\r\n                        <time>{0}</" +
"time>\r\n                        <span>{1}</span>\r\n                    </div>`;\r\n\r" +
"\n        html = window.stringFormat(html, timestamp, msg);\r\n\r\n        $(\".eod.me" +
"ssages\").append(html);\r\n        counter++;\r\n\r\n        $(\'#EODSegment\').scrollTop" +
"($(\'#EODSegment\')[0].scrollHeight - $(\'#EODSegment\')[0].clientHeight);\r\n    };\r\n" +
"\r\n    function ShowProgress(counter) {\r\n        if (receivingData) {\r\n          " +
"  if (counter >= 100 || counter <= 0) {\r\n                if (toggle === true) {\r" +
"\n                    toggle = false;\r\n                } else {\r\n                " +
"    toggle = true;\r\n                }\r\n            };\r\n\r\n            if (toggle)" +
" {\r\n                counter++;\r\n            } else {\r\n                counter--;" +
"\r\n            };\r\n\r\n            $(\'.progress\').progress({\r\n                perce" +
"nt: counter,\r\n                limitValues: true,\r\n                label: \"ratio\"" +
"\r\n            });\r\n\r\n            setTimeout(ShowProgress, 100, counter);\r\n\r\n    " +
"    } else {\r\n            $(\'.progress\').progress({\r\n                percent: 10" +
"0,\r\n                limitValues: true,\r\n                label: \"ratio\"\r\n        " +
"    });\r\n        };\r\n    };\r\n\r\n    function notifyServer() {\r\n        function r" +
"equest() {\r\n            const url = \"/dashboard/finance/tasks/eod-processing/sta" +
"rt-new-day\";\r\n            return window.getAjaxRequest(url, \"PUT\");\r\n        };\r" +
"\n\r\n        const ajax = request();\r\n\r\n        ajax.success(function () {\r\n      " +
"      //Okay\r\n        });\r\n\r\n        ajax.fail(function (xhr) {\r\n            win" +
"dow.logAjaxErrorMessage(xhr);\r\n        });\r\n\r\n    };\r\n\r\n    var sendMessage = fu" +
"nction () {\r\n        const elapsed = parseInt((new Date - start) / 1000);\r\n     " +
"   const progress = parseInt((elapsed / counter) * 100);\r\n\r\n        if (progress" +
" > 100) {\r\n            clearInterval(interval);\r\n            return;\r\n        };" +
"\r\n\r\n        $.connection.baseHub.server.terminate(progress);\r\n        //localSto" +
"rage.removeItem(\"access_token\");\r\n    };\r\n</script>");

        }
    }
}
#pragma warning restore 1591
