#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    #line 1 "..\..\Views\Tasks\JournalEntry\Index.cshtml"
    using MixERP.Finance.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/JournalEntry/Index.cshtml")]
    public partial class _Views_Tasks_JournalEntry_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_JournalEntry_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\JournalEntry\Index.cshtml"
  
    ViewBag.Title = "Journal Entries";
    Layout = ViewBag.FinanceLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 10 "..\..\Views\Tasks\JournalEntry\Index.cshtml"
Write(Html.PartialView("Shared/JournalView.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral(@"

<script>
    window.prepareView({
        Title: ""Journal Entries"",
        AddNewText: ""Add New"",
        AddNewUrl: ""/dashboard/finance/tasks/journal/entry/new"",
        ReturnText: ""Return"",
        ReturnUrl: ""javascript:void(0);"",
        Book: ""Journal Entry"",
        ChecklistUrl: ""/dashboard/finance/tasks/journal/checklist/{tranId}""
    });
</script>");

        }
    }
}
#pragma warning restore 1591
