#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    
    using Frapid.WebsiteBuilder;
    using MixERP.Finance;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/JournalEntry/New.cshtml")]
    public partial class _Views_Tasks_JournalEntry_New_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_JournalEntry_New_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\JournalEntry\New.cshtml"
  
    ViewBag.Title = "Bank Accounts";
    Layout = ViewBag.FinanceLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"ui attached page segment\"");

WriteLiteral(" style=\"min-height: 100%;padding:3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Add a New Journal Entry</div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui form segment\"");

WriteLiteral(" style=\"width:700px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"three fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ValueDateTextBox\"");

WriteLiteral(">\r\n                    Value Date\r\n                </label>\r\n                <inp" +
"ut");

WriteLiteral(" id=\"ValueDateTextBox\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"BookDateTextBox\"");

WriteLiteral(">\r\n                    Book Date\r\n                </label>\r\n                <inpu" +
"t");

WriteLiteral(" id=\"BookDateTextBox\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ReferenceNumberInputText\"");

WriteLiteral(">\r\n                    Reference Number\r\n                </label>\r\n              " +
"  <input");

WriteLiteral(" id=\"ReferenceNumberInputText\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <input");

WriteLiteral(" id=\"TransactionGridViewHidden\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" style=\"width: 100%; overflow: auto;\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"TransactionGridView\"");

WriteLiteral(" class=\"ui table segment\"");

WriteLiteral(" style=\"min-width: 1200px; max-width: 2000px;\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" style=\"width: 9%\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"StatementReferenceInputText\"");

WriteLiteral(">\r\n                            Statement Reference\r\n                        </lab" +
"el>\r\n                    </th>\r\n                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" style=\"width: 7%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"AccountNumberInputText\"");

WriteLiteral(">\r\n                            Account Number\r\n                        </label>\r\n" +
"                    </th>\r\n                    <th");

WriteLiteral(" style=\"width: 15%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"AccountSelect\"");

WriteLiteral(">\r\n                            Account\r\n                        </label>\r\n       " +
"             </th>\r\n                    <th");

WriteLiteral(" style=\"width: 8%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"CashRepositorySelect\"");

WriteLiteral(">\r\n                            Cash Repository\r\n                        </label>\r" +
"\n                    </th>\r\n                    <th");

WriteLiteral(" style=\"width: 8%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"CurrencySelect\"");

WriteLiteral(">\r\n                            Currency\r\n                        </label>\r\n      " +
"              </th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width: 10%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"DebitInputText\"");

WriteLiteral(">\r\n                            Debit\r\n                        </label>\r\n         " +
"           </th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width: 9%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"CreditInputText\"");

WriteLiteral(">\r\n                            Credit\r\n                        </label>\r\n        " +
"            </th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width: 7%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"ERInputText\"");

WriteLiteral(">\r\n                            ER\r\n                        </label>\r\n            " +
"        </th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width: 9%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"LCDebitInputText\"");

WriteLiteral(">\r\n                            LC Debit\r\n                        </label>\r\n      " +
"              </th>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"width: 9%;\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"LCCreditInputText\"");

WriteLiteral(">\r\n                            LC Credit\r\n                        </label>\r\n     " +
"               </th>\r\n                    <th");

WriteLiteral(" style=\"width: 9%;\"");

WriteLiteral(">\r\n                        Action\r\n                    </th>\r\n                </t" +
"r>\r\n            </thead>\r\n            <tbody>\r\n                <tr");

WriteLiteral(" class=\"ui form footer-row\"");

WriteLiteral(">\r\n                    <td>\r\n                        <input");

WriteLiteral(" id=\"StatementReferenceInputText\"");

WriteLiteral(" title=\"Ctrl + Alt +S\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"input");

WriteLiteral(" id=\"AccountNumberInputText\"");

WriteLiteral(" title=\"Ctrl + Alt + T\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"select");

WriteLiteral(" id=\"AccountSelect\"");

WriteLiteral(" title=\"Ctrl + Alt + A\"");

WriteLiteral("></select>\r\n                    </td>\r\n                    <td>\r\n                " +
"        <select");

WriteLiteral(" id=\"CashRepositorySelect\"");

WriteLiteral("></select>\r\n                    </td>\r\n                    <td>\r\n                " +
"        <select");

WriteLiteral(" id=\"CurrencySelect\"");

WriteLiteral("></select>\r\n                    </td>\r\n                    <td>\r\n                " +
"        <input");

WriteLiteral(" id=\"DebitInputText\"");

WriteLiteral(" class=\"text-right currency\"");

WriteLiteral(" title=\"Ctrl + Alt + D\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"input");

WriteLiteral(" id=\"CreditInputText\"");

WriteLiteral(" class=\"text-right currency\"");

WriteLiteral(" title=\"Ctrl + Alt + C\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"input");

WriteLiteral(" id=\"ERInputText\"");

WriteLiteral(" class=\"text-right decimal\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"input");

WriteLiteral(" id=\"LCDebitInputText\"");

WriteLiteral(" class=\"text-right currency\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" title=\"Ctrl + Alt + D\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"input");

WriteLiteral(" id=\"LCCreditInputText\"");

WriteLiteral(" class=\"text-right currency\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" title=\"Ctrl + Alt + C\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                    </td>\r\n                    <td>\r\n                        <" +
"input");

WriteLiteral(" id=\"AddInputButton\"");

WriteLiteral(" class=\"ui small blue button\"");

WriteLiteral(" title=\"Ctrl + Return\"");

WriteLiteral(" value=\"Add\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                    </td>\r\n                </tr>\r\n            </tbody>\r\n      " +
"  </table>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui form segment\"");

WriteLiteral(" style=\"width: 700px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"CostCenterSelect\"");

WriteLiteral(">\r\n                Cost Center\r\n            </label>\r\n            <select");

WriteLiteral(" id=\"CostCenterSelect\"");

WriteLiteral("></select>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"DebitTotalTextBox\"");

WriteLiteral(">\r\n                Debit Total\r\n            </label>\r\n            <input");

WriteLiteral(" id=\"DebitTotalTextBox\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" class=\"text-right currency\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"CreditTotalLiteral\"");

WriteLiteral(">\r\n                Credit Total\r\n            </label>\r\n            <input");

WriteLiteral(" id=\"CreditTotalTextBox\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" class=\"text-right currency\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" id=\"PostButton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("  class=\"ui small positive button\"");

WriteLiteral(">\r\n                Post Transaction\r\n            </button>\r\n            <a");

WriteLiteral(" href=\"/dashboard/finance/tasks/journal/entry\"");

WriteLiteral(" onclick=\"return (confirm(\'Are you sure?\'))\"");

WriteLiteral(" class=\"ui small blue button\"");

WriteLiteral(">Return Back</a>            \r\n        </div>\r\n    </div>\r\n    <span");

WriteLiteral(" id=\"ErrorLabelBottom\"");

WriteLiteral(" class=\"big error\"");

WriteLiteral("></span>\r\n</div>\r\n\r\n<script>\r\n    var addInputButton = $(\"#AddInputButton\");\r\n   " +
" var accountNumberInputText = $(\"#AccountNumberInputText\");\r\n    var accountSele" +
"ct = $(\"#AccountSelect\");\r\n    var attachmentDiv = $(\"#AttachmentDiv\");\r\n    var" +
" attachmentLabel = $(\"#AttachmentLabel\");\r\n\r\n    var cashRepositorySelect = $(\"#" +
"CashRepositorySelect\");\r\n    var costCenterSelect = $(\"#CostCenterSelect\");\r\n   " +
" var creditInputText = $(\"#CreditInputText\");\r\n\r\n    var creditTotalTextBox = $(" +
"\"#CreditTotalTextBox\");\r\n    var currencySelect = $(\"#CurrencySelect\");\r\n\r\n    v" +
"ar debitInputText = $(\"#DebitInputText\");\r\n    var debitTotalTextBox = $(\"#Debit" +
"TotalTextBox\");\r\n\r\n    var errorLabelBottom = $(\"#ErrorLabelBottom\");\r\n    var e" +
"rInputText = $(\"#ERInputText\");\r\n\r\n    var lcCreditInputText = $(\"#LCCreditInput" +
"Text\");\r\n    var lcDebitInputText = $(\"#LCDebitInputText\");\r\n\r\n    var postButto" +
"n = $(\"#PostButton\");\r\n\r\n    var referenceNumberInputText = $(\"#ReferenceNumberI" +
"nputText\");\r\n\r\n    var statementReferenceInputText = $(\"#StatementReferenceInput" +
"Text\");\r\n\r\n    var transactionGridView = $(\"#TransactionGridView\");\r\n    var tra" +
"nsactionGridViewHidden = $(\"#TransactionGridViewHidden\");\r\n\r\n    var valueDateTe" +
"xtBox = $(\"#ValueDateTextBox\");\r\n    var bookDateTextBox = $(\"#BookDateTextBox\")" +
";\r\n\r\n    //Variables\r\n    var accountNumber = \"\";\r\n    var account = \"\";\r\n    va" +
"r attachments;\r\n\r\n    var cashRepositoryCode = \"\";\r\n    var costCenterId = 0;\r\n " +
"   var credit = 0;\r\n    var currencyCode = \'\';\r\n\r\n    var debit = 0;\r\n\r\n    var " +
"lcCredit = 0;\r\n    var lcDebit = 0;\r\n    var er = 0.00;\r\n\r\n    var valueDate;\r\n " +
"   var bookDate;\r\n\r\n    var url = \"\";\r\n    var data = \"\";\r\n    var referenceNumb" +
"er = \"\";\r\n    var statementReference = \"\";\r\n\r\n    function addLoader(el) {\r\n    " +
"    el.addClass(\"loading\");\r\n    };\r\n\r\n    function removeLoader(el) {\r\n        " +
"el.removeClass(\"loading\");\r\n    };\r\n\r\n\r\n    //Utilities\r\n    var addShortcuts = " +
"function () {\r\n        \"use strict\";\r\n\r\n        shortcut.add(\"CTRL+ALT+T\", funct" +
"ion () {\r\n            $(\'#AccountNumberTextBox\').focus();\r\n        });\r\n\r\n      " +
"  shortcut.add(\"CTRL+ALT+A\", function () {\r\n            $(\'#AccountSelect\').focu" +
"s();\r\n        });\r\n\r\n        shortcut.add(\"CTRL+ALT+S\", function () {\r\n         " +
"   $(\'#StatementReferenceTextBox\').focus();\r\n        });\r\n\r\n        shortcut.add" +
"(\"CTRL+ALT+D\", function () {\r\n            $(\'#lcDebitTextBox\').focus();\r\n       " +
" });\r\n\r\n        shortcut.add(\"CTRL+ALT+C\", function () {\r\n            $(\'#lcCred" +
"itTextBox\').focus();\r\n        });\r\n\r\n        shortcut.add(\"CTRL+RETURN\", functio" +
"n () {\r\n            $(\'#AddInputButton\').click();\r\n        });\r\n    };\r\n\r\n\r\n    " +
"function createCascadingPair(select, input) {\r\n        input.blur(function () {\r" +
"\n            selectDropDownListByValue(this.id, select.attr(\"id\"));\r\n        });" +
"\r\n\r\n        select.change(function () {\r\n            input.val(select.getSelecte" +
"dValue());\r\n        });\r\n    };\r\n\r\n    var selectDropDownListByValue = function " +
"(textBoxId, dropDownListId) {\r\n        var listControl = $(\"#\" + dropDownListId)" +
";\r\n        var textBox = $(\"#\" + textBoxId);\r\n        var selectedValue = textBo" +
"x.val();\r\n        var exists;\r\n\r\n        if (isNullOrWhiteSpace(textBox.val())) " +
"{\r\n            return;\r\n        };\r\n\r\n        if (listControl.length) {\r\n       " +
"     listControl.find(\'option\').each(function () {\r\n                if (this.val" +
"ue === selectedValue) {\r\n                    exists = true;\r\n                }\r\n" +
"            });\r\n        }\r\n\r\n        if (exists) {\r\n            listControl.val" +
"(selectedValue).trigger(\'change\');\r\n        } else {\r\n            textBox.val(\'\'" +
").trigger(\'change\');\r\n        }\r\n\r\n        triggerChange(dropDownListId);\r\n    }" +
";\r\n\r\n\r\n    //Page Load Event\r\n    $(document).ready(function () {\r\n        \"use " +
"strict\";\r\n        addShortcuts();\r\n        initializeAjaxData();\r\n        create" +
"CascadingPair(accountSelect, accountNumberInputText);\r\n    });\r\n\r\n    function i" +
"nitializeAjaxData() {\r\n        loadAccounts();\r\n        loadCostCenters();\r\n    " +
"};\r\n\r\n    function loadAccounts() {\r\n        function request() {\r\n            u" +
"rl = \"/dashboard/finance/chart-of-accounts/list\";\r\n            return window.get" +
"AjaxRequest(url);\r\n        };\r\n\r\n        var ajax = request();\r\n\r\n        ajax.s" +
"uccess(function (response) {\r\n            var options = \"<option>Select</option>" +
"\";\r\n\r\n            $.each(response, function () {\r\n                var option = \"" +
"<option value=\'{accountNumber}\' data-account-master-id=\'{accountMasterId}\' data-" +
"currency-code=\'{currencyCode}\'>{accountName}</option>\";\r\n                option " +
"= option.replace(\"{accountNumber}\", this.AccountNumber);\r\n                option" +
" = option.replace(\"{accountName}\", this.AccountName);\r\n                option = " +
"option.replace(\"{accountMasterId}\", this.AccountMasterId);\r\n                opti" +
"on = option.replace(\"{currencyCode}\", this.CurrencyCode);\r\n\r\n                opt" +
"ions += option;\r\n            });\r\n\r\n            accountSelect.html(options);\r\n  " +
"      });\r\n\r\n        ajax.fail(function (xhr) {\r\n            alert(JSON.stringif" +
"y(xhr));\r\n        });\r\n    };\r\n\r\n    function loadCashRepositories() {\r\n        " +
"var url = \"/api/forms/finance/cash-repositories/lookup-fields\";\r\n        window." +
"ajaxDataBind(url, cashRepositorySelect, null, null, null, null, \"Key\", \"Value\");" +
"\r\n    };\r\n\r\n    function loadCostCenters() {\r\n        url = \"/api/forms/finance/" +
"cost-centers/display-fields\";\r\n        window.ajaxDataBind(url, costCenterSelect" +
", null, null, null, null, \"Key\", \"Value\");\r\n    };\r\n\r\n    function loadCurrencie" +
"s() {\r\n        url = \"/api/forms/core/currencies/lookup-fields\";\r\n        window" +
".ajaxDataBind(url, currencySelect, null, null, null, null, \"Key\", \"Key\");\r\n    }" +
";\r\n\r\n    //Control Events\r\n    accountSelect.change(function () {\r\n        accou" +
"ntNumberInputText.val(accountSelect.getSelectedValue());\r\n    });\r\n\r\n    functio" +
"n isCashAccount() {\r\n        var selectedAccount = accountSelect.find(\"option:se" +
"lected\");\r\n        var accountMasterId = parseInt(selectedAccount.attr(\"data-acc" +
"ount-master-id\"));\r\n        if (accountMasterId === 10101) {\r\n            return" +
" true;\r\n        };\r\n\r\n        return false;\r\n    };\r\n\r\n    accountSelect.blur(fu" +
"nction () {\r\n        function loadCurrency(selectedAccount) {\r\n            var c" +
"urrencyCode = selectedAccount.attr(\"data-currency-code\");\r\n\r\n            var opt" +
"ion = \"<option value=\'{currencyCode}\'>{currencyCode}</option>\";\r\n            opt" +
"ion = option.replace(/{currencyCode}/g, currencyCode);\r\n\r\n            currencySe" +
"lect.html(option);\r\n        };\r\n\r\n        var selectedAccount = accountSelect.fi" +
"nd(\"option:selected\");\r\n        loadCurrency(selectedAccount);\r\n\r\n\r\n        //Ca" +
"sh Account\r\n        if (isCashAccount()) {\r\n            loadCashRepositories();\r" +
"\n            loadCurrencies();\r\n        } else {\r\n            cashRepositorySele" +
"ct.html(\"\");\r\n        };\r\n    });\r\n\r\n    addInputButton.click(function () {\r\n   " +
"     statementReference = statementReferenceInputText.val();\r\n        accountNum" +
"ber = accountNumberInputText.val();\r\n        account = accountSelect.getSelected" +
"Text();\r\n        cashRepositoryCode = cashRepositorySelect.getSelectedValue();\r\n" +
"\r\n        currencyCode = currencySelect.getSelectedValue();\r\n\r\n        debit = p" +
"arseFloat(debitInputText.val() || 0);\r\n        credit = parseFloat(creditInputTe" +
"xt.val() || 0);\r\n\r\n        er = parseFloat(erInputText.val() || 0);\r\n\r\n        l" +
"cDebit = parseFloat(lcDebitInputText.val() || 0);\r\n        lcCredit = parseFloat" +
"(lcCreditInputText.val() || 0);\r\n\r\n        if (window.isNullOrWhiteSpace(stateme" +
"ntReference)) {\r\n            window.makeDirty(statementReferenceInputText);\r\n   " +
"         return;\r\n        };\r\n\r\n        window.removeDirty(statementReferenceInp" +
"utText);\r\n\r\n        if (window.isNullOrWhiteSpace(accountNumberInputText.val()))" +
" {\r\n            window.makeDirty(accountNumberInputText);\r\n            return;\r\n" +
"        };\r\n\r\n        window.removeDirty(accountNumberInputText);\r\n\r\n        if " +
"(window.isNullOrWhiteSpace(accountSelect.getSelectedText())) {\r\n            wind" +
"ow.makeDirty(accountSelect);\r\n            return;\r\n        };\r\n\r\n        window." +
"removeDirty(accountSelect);\r\n\r\n\r\n        if (er <= 0) {\r\n            window.make" +
"Dirty(erInputText);\r\n            return;\r\n        };\r\n\r\n        window.removeDir" +
"ty(erInputText);\r\n\r\n        if ((debit > 0 && credit > 0) || (debit === 0 && cre" +
"dit === 0)) {\r\n            window.makeDirty(debitInputText);\r\n            window" +
".makeDirty(creditInputText);\r\n            return;\r\n        };\r\n\r\n        if ((lc" +
"Debit > 0 && lcCredit > 0) || (lcDebit === 0 && lcCredit === 0)) {\r\n            " +
"window.makeDirty(lcDebitInputText);\r\n            window.makeDirty(lcCreditInputT" +
"ext);\r\n            return;\r\n        };\r\n\r\n        if (lcDebit < 0) {\r\n          " +
"  window.makeDirty(lcDebitInputText);\r\n            return;\r\n        };\r\n\r\n      " +
"  if (lcCredit < 0) {\r\n            window.makeDirty(lcCreditInputText);\r\n       " +
"     return;\r\n        };\r\n\r\n        window.removeDirty(debitInputText);\r\n       " +
" window.removeDirty(creditInputText);\r\n        window.removeDirty(lcDebitInputTe" +
"xt);\r\n        window.removeDirty(lcCreditInputText);\r\n        window.removeDirty" +
"(cashRepositorySelect);\r\n\r\n        if (cashRepositorySelect.find(\"option\").size(" +
") > 1 && window.isNullOrWhiteSpace(cashRepositorySelect.getSelectedValue())) {\r\n" +
"            $.notify(\"Invalid cash repository specified.\");\r\n            return;" +
"\r\n        };\r\n\r\n        var isCash = isCashAccount();\r\n\r\n        if (isCash) {\r\n" +
"            if (window.isNullOrWhiteSpace(cashRepositoryCode)) {\r\n              " +
"  window.makeDirty(cashRepositorySelect);\r\n                $.notify(\"Invalid cas" +
"h repository specified.\", \"error\");\r\n                return;\r\n            };\r\n  " +
"      } else {\r\n            if (!window.isNullOrWhiteSpace(cashRepositoryCode)) " +
"{\r\n                $.notify(\"Invalid cash repository specified.\");\r\n            " +
"    window.makeDirty(cashRepositorySelect);\r\n                return;\r\n          " +
"  };\r\n\r\n            addLoader(transactionGridView);\r\n            addRow(statemen" +
"tReference, accountNumber, account, \"\", currencyCode, debit, credit, er, lcDebit" +
", lcCredit, false);\r\n            return;\r\n        };\r\n\r\n\r\n        addLoader(tran" +
"sactionGridView);\r\n\r\n\r\n        if (debit > 0) {\r\n            addRow(statementRef" +
"erence, accountNumber, account, cashRepositoryCode, currencyCode, debit, credit," +
" er, lcDebit, lcCredit, true);\r\n            return;\r\n        } else {\r\n         " +
"   if (isCash) {\r\n                var ajaxHasBalance = hasBalance(cashRepository" +
"Code, currencyCode, credit);\r\n\r\n                ajaxHasBalance.fail(function (xh" +
"r) {\r\n                    removeLoader(transactionGridView);\r\n                  " +
"  logAjaxErrorMessage(xhr);\r\n                });\r\n\r\n                ajaxHasBalan" +
"ce.success(function (response) {\r\n                    var hasBalance = response;" +
"\r\n\r\n                    if (!hasBalance) {\r\n                        $.notify(\"No" +
"t enough balance in the cash repository \" + cashRepositoryCode, \"error\");\r\n     " +
"                   removeLoader(transactionGridView);\r\n                        w" +
"indow.makeDirty(cashRepositorySelect);\r\n                        return;\r\n       " +
"             };\r\n\r\n                    addRow(statementReference, accountNumber," +
" account, cashRepositoryCode, currencyCode, debit, credit, er, lcDebit, lcCredit" +
", true);\r\n                });\r\n            };\r\n        };\r\n    });\r\n\r\n    var ad" +
"dRow = function (statementReference, accountNumber, account, cashRepository, cur" +
"rencyCode, debit, credit, er, lcDebit, lcCredit, isCash) {\r\n        var grid = t" +
"ransactionGridView;\r\n        var rows = grid.find(\"tbody tr:not(:last-child)\");\r" +
"\n        var duplicateEntry = false;\r\n\r\n        if (!currencyCode) {\r\n          " +
"  window.makeDirty(currencySelect);\r\n            removeLoader(transactionGridVie" +
"w);\r\n            return;\r\n        };\r\n\r\n        window.removeDirty(currencySelec" +
"t);\r\n\r\n        rows.each(function () {\r\n            var row = $(this);\r\n\r\n      " +
"      if (!isCash) {\r\n                if (window.getColumnText(row, 1) === accou" +
"ntNumber) {\r\n                    $.notify(\"Duplicate entry.\");\r\n                " +
"    window.makeDirty(accountNumberInputText);\r\n                    duplicateEntr" +
"y = true;\r\n\r\n                    removeLoader(transactionGridView);\r\n           " +
"         return;\r\n                };\r\n            };\r\n\r\n            if (isCash) " +
"{\r\n                if (window.getColumnText(row, 3) === cashRepository) {\r\n     " +
"               $.notify(\"Duplicate entry\");\r\n                    window.makeDirt" +
"y(accountNumberInputText);\r\n                    duplicateEntry = true;\r\n        " +
"        };\r\n            };\r\n        });\r\n\r\n        if (duplicateEntry) {\r\n      " +
"      removeLoader(transactionGridView);\r\n            return;\r\n        };\r\n\r\n   " +
"     var html = \"<tr class=\'grid2-row\'><td>\" + statementReference + \"</td><td>\" " +
"+ accountNumber + \"</td><td>\" + account + \"</td><td>\" + cashRepository + \"</td><" +
"td>\" + currencyCode + \"</td><td class=\'text-right\'>\" + window.getFormattedNumber" +
"(debit) + \"</td><td class=\'text-right\'>\" + window.getFormattedNumber(credit) + \"" +
"</td>\"\r\n            + \"<td class=\'text-right\'>\" + window.getFormattedNumber(er) " +
"+ \"</td><td class=\'text-right\'>\" + window.getFormattedNumber(lcDebit) + \"</td><t" +
"d class=\'text-right\'>\" + window.getFormattedNumber(lcCredit) + \"</td>\"\r\n        " +
"    + \"<td><a class=\'pointer\' onclick=\'removeRow($(this));\'><i class=\'ui delete " +
"icon\'></i></a><a class=\'pointer\' onclick=\'toggleDanger($(this));\'><i class=\'ui p" +
"ointer check mark icon\'></a></i><a class=\'pointer\' onclick=\'toggleSuccess($(this" +
"));\'><i class=\'ui pointer thumbs up icon\'></i></a></td></tr>\";\r\n        grid.fin" +
"d(\"tr:last\").before(html);\r\n\r\n        summate();\r\n\r\n        lcDebitInputText.val" +
"(\"\");\r\n        lcCreditInputText.val(\"\");\r\n        debitInputText.val(\"\");\r\n    " +
"    creditInputText.val(\"\");\r\n\r\n        creditInputText.prop(\"disabled\", false);" +
"\r\n\r\n        removeLoader(transactionGridView);\r\n        window.repaint();\r\n     " +
"   statementReferenceInputText.focus();\r\n    };\r\n\r\n    attachmentLabel.on(\"click" +
"\", function () {\r\n        attachmentDiv.toggle(500);\r\n    });\r\n\r\n    currencySel" +
"ect.blur(function () {\r\n        var ajaxGetExchangeRate = getExchangeRate(curren" +
"cySelect.getSelectedValue());\r\n\r\n        ajaxGetExchangeRate.done(function (resp" +
"onse) {\r\n            erInputText.val(response);\r\n        });\r\n\r\n        ajaxGetE" +
"xchangeRate.fail(function (xhr) {\r\n            window.logAjaxErrorMessage(xhr);\r" +
"\n        });\r\n    });\r\n\r\n    debitInputText.blur(function () {\r\n        debit = " +
"parseFloat(debitInputText.val() || 0);\r\n\r\n        if (debit > 0) {\r\n            " +
"creditInputText.prop(\"disabled\", true);\r\n            erInputText.focus();\r\n     " +
"       return;\r\n        };\r\n\r\n        creditInputText.prop(\"disabled\", false);\r\n" +
"    });\r\n\r\n    debitInputText.keyup(function () {\r\n        UpdateLocalCurrencies" +
"();\r\n    });\r\n\r\n    creditInputText.keyup(function () {\r\n        UpdateLocalCurr" +
"encies();\r\n    });\r\n\r\n    erInputText.keyup(function () {\r\n        UpdateLocalCu" +
"rrencies();\r\n    });\r\n\r\n    function UpdateLocalCurrencies() {\r\n        er = par" +
"seFloat(erInputText.val() || 0);\r\n\r\n        if (er > 0) {\r\n            lcDebitIn" +
"putText.val(parseFloat(debitInputText.val() || 0) * er);\r\n            lcCreditIn" +
"putText.val(parseFloat(creditInputText.val() || 0) * er);\r\n        };\r\n    };\r\n\r" +
"\n    postButton.click(function () {\r\n        valueDate = window.parseLocalizedDa" +
"te(valueDateTextBox.val());\r\n        bookDate = window.parseLocalizedDate(bookDa" +
"teTextBox.val());\r\n        referenceNumber = referenceNumberInputText.getSelecte" +
"dValue();\r\n        costCenterId = parseInt(costCenterSelect.getSelectedValue() |" +
"| 0);\r\n\r\n        if (validate()) {\r\n            post();\r\n        };\r\n    });\r\n\r\n" +
"    var post = function () {\r\n        function request(model) {\r\n            var" +
" url = \"/dashboard/finance/tasks/journal/entry/new\";\r\n            var data = JSO" +
"N.stringify(model);\r\n\r\n            return window.getAjaxRequest(url, \"POST\", dat" +
"a);\r\n        };\r\n\r\n        var model = getModel();\r\n\r\n        var ajax = request" +
"(model);\r\n\r\n        ajax.success(function (response) {\r\n            var id = res" +
"ponse;\r\n            window.location = \"/dashboard/finance/tasks/journal/checklis" +
"t/\" + id;\r\n        });\r\n\r\n        ajax.fail(function (xhr) {\r\n            window" +
".logAjaxErrorMessage(xhr);\r\n\r\n            var errorMessage = window.getAjaxError" +
"Message(xhr);\r\n            errorLabelBottom.html(errorMessage);\r\n        });\r\n  " +
"  };\r\n\r\n    function getModel() {\r\n        var details = [];\r\n\r\n        transact" +
"ionGridView.find(\"tbody tr:not(:last-child)\")\r\n            .each(function () {\r\n" +
"                var row = $(this);\r\n                var statementReference = row" +
".find(\"td:nth-child(1)\").text();\r\n                var accountNumber = row.find(\"" +
"td:nth-child(2)\").text();\r\n                var account = row.find(\"td:nth-child(" +
"3)\").text();\r\n                var cashRepositoryCode = (row.find(\"td:nth-child(4" +
")\").text() || null);\r\n                var currencyCode = row.find(\"td:nth-child(" +
"5)\").text();\r\n                var debit = window.parseFloat2(row.find(\"td:nth-ch" +
"ild(6)\").text());\r\n                var credit = window.parseFloat2(row.find(\"td:" +
"nth-child(7)\").text());\r\n                var er = window.parseFloat2(row.find(\"t" +
"d:nth-child(8)\").text());\r\n                var lcDebit = window.parseFloat2(row." +
"find(\"td:nth-child(9)\").text());\r\n                var lcCredit = window.parseFlo" +
"at2(row.find(\"td:nth-child(10)\").text());\r\n\r\n\r\n                details.push({\r\n " +
"                   Account: account,\r\n                    AccountNumber: account" +
"Number,\r\n                    CashRepositoryCode: cashRepositoryCode,\r\n          " +
"          Credit: credit,\r\n                    CurrencyCode: currencyCode,\r\n    " +
"                Debit: debit,\r\n                    ExchangeRate: er,\r\n          " +
"          LocalCurrencyCredit: lcCredit,\r\n                    LocalCurrencyDebit" +
": lcDebit,\r\n                    StatementReference: statementReference\r\n        " +
"        });\r\n            });\r\n\r\n        var model = {\r\n            ValueDate: va" +
"lueDate,\r\n            BookDate: bookDate,\r\n            ReferenceNumber: referenc" +
"eNumber,\r\n            CostCenterId: costCenterId,\r\n            Details: details," +
"\r\n            Attachemnts: []\r\n        };\r\n\r\n        return model;\r\n    };\r\n\r\n  " +
"  var validate = function () {\r\n        errorLabelBottom.html(\"\");\r\n\r\n        wi" +
"ndow.removeDirty(valueDateTextBox);\r\n        window.removeDirty(referenceNumberI" +
"nputText);\r\n        window.removeDirty(statementReferenceInputText);\r\n        wi" +
"ndow.removeDirty(accountNumberInputText);\r\n        window.removeDirty(accountSel" +
"ect);\r\n        window.removeDirty(cashRepositorySelect);\r\n        window.removeD" +
"irty(lcDebitInputText);\r\n        window.removeDirty(lcCreditInputText);\r\n       " +
" window.removeDirty(costCenterSelect);\r\n\r\n        if (!window.isDate(valueDate))" +
" {\r\n            window.makeDirty(valueDateTextBox);\r\n            errorLabelBotto" +
"m.html(\"Invalid Date\");\r\n            return false;\r\n        };\r\n\r\n        if (pa" +
"rseInt(costCenterSelect.getSelectedValue() || 0) <= 0) {\r\n            window.mak" +
"eDirty(costCenterSelect);\r\n            errorLabelBottom.html(\"Invalid cost cente" +
"r.\");\r\n            return false;\r\n        };\r\n\r\n\r\n        if (transactionGridVie" +
"w.find(\"tr\").length === 2) {\r\n            errorLabelBottom.html(\"Gridview is emp" +
"ty.\");\r\n            return false;\r\n        };\r\n\r\n        var rows = transactionG" +
"ridView.find(\"tr:not(:first-child):not(:last-child)\");\r\n\r\n        if (rows.each(" +
"function () {\r\n            var row = $(this);\r\n\r\n            debit = window.pars" +
"eFloat2(window.getColumnText(row, 8));\r\n            credit = window.parseFloat2(" +
"window.getColumnText(row, 9));\r\n\r\n            if (debit > 0 && credit > 0) {\r\n  " +
"              window.addDanger(row);\r\n                return false;\r\n        };\r" +
"\n\r\n            if (debit < 0 || credit < 0) {\r\n                window.addDanger(" +
"row);\r\n                return false;\r\n        };\r\n\r\n            if (debit === 0 " +
"&& credit === 0) {\r\n                window.addDanger(row);\r\n                retu" +
"rn false;\r\n        };\r\n\r\n            return true;\r\n        }) === false) {\r\n    " +
"        return false;\r\n        };\r\n\r\n        summate();\r\n\r\n        if (parseFloa" +
"t(debitTotalTextBox.val() || 0) !== parseFloat(creditTotalTextBox.val() || 0)) {" +
"\r\n            $.notify(\"Referencing sides are not equal.\", \"error\");\r\n          " +
"  return false;\r\n        };\r\n\r\n        return true;\r\n    };\r\n\r\n    //GridView Da" +
"ta Function\r\n\r\n    //GridView Manipulation\r\n\r\n    //Ajax Requests\r\n    function " +
"getExchangeRate(currencyCode) {\r\n        url = \"/dashboard/finance/currency/exch" +
"ange-rate/of/{currencyCode}\";\r\n        url = url.replace(\"{currencyCode}\", curre" +
"ncyCode);\r\n\r\n        return window.getAjaxRequest(url);\r\n    };\r\n\r\n    function " +
"hasBalance(cashRepositoryCode, currencyCode, amount) {\r\n        url = \"/dashboar" +
"d/finance/cash-repository/check-balance/{cashRepositoryCode}/{currencyCode}/{amo" +
"unt}\";\r\n        url = url.replace(\"{cashRepositoryCode}\", cashRepositoryCode);\r\n" +
"        url = url.replace(\"{currencyCode}\", currencyCode);\r\n        url = url.re" +
"place(\"{amount}\", credit);\r\n\r\n\r\n        return window.getAjaxRequest(url);\r\n    " +
"};\r\n\r\n    //Boolean Validation\r\n\r\n    //Validation Helper Functions\r\n\r\n    //Log" +
"ic & Validation\r\n    var summate = function () {\r\n        var debitTotal = parse" +
"Float(window.sumOfColumn(\"#\" + transactionGridView.attr(\"id\"), 8) || 0);\r\n      " +
"  var creditTotal = parseFloat(window.sumOfColumn(\"#\" + transactionGridView.attr" +
"(\"id\"), 9) || 0);\r\n\r\n        debitTotalTextBox.val(debitTotal);\r\n        creditT" +
"otalTextBox.val(creditTotal);\r\n    };\r\n\r\n\r\n    $(document).ajaxStop(function () " +
"{\r\n        var importModel = window.localStorage.getItem(\'ImportModel\');\r\n      " +
"  localStorage.removeItem(\'ImportModel\');\r\n\r\n        if (!importModel) {\r\n      " +
"      return;\r\n        };\r\n\r\n        importModel = JSON.parse(importModel);\r\n\r\n\r" +
"\n        valueDateTextBox.val(importModel.valueDate);\r\n        bookDateTextBox.v" +
"al(importModel.bookDate);\r\n        referenceNumberInputText.val(importModel.refe" +
"renceNumber);\r\n        costCenterSelect.val(importModel.costCenter.toString());\r" +
"\n\r\n        $.each(importModel.table, function (i, v) {\r\n            addRow(v[0]," +
" v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8], v[9]);\r\n        });\r\n    });\r\n\r" +
"\n    window.overridePath = \"/dashboard/finance/tasks/journal/entry\";\r\n</script>");

        }
    }
}
#pragma warning restore 1591
